### ISSUE TITLE
ExtraContexts causes server crash

### ISSUE THREAD

**Issue by SrBedrock** [LuckPerms/ExtraContexts#15]
Luck Perms Version: 5.0.9
Luck Perms Extensions: extension-legacy-api

[ExtraContent Version: jenkins build 12](https://ci.lucko.me/job/ExtraContexts/)
[ExtraContent config.yml](https://hasteb.in/ewuhomap.yaml)

Server Version: Paper 230

[Console Error](https://hasteb.in/ecotajax.md)

**Comment by lucko** [comment]
Are you actually using all of those placeholders as contexts?

**Comment by SrBedrock** [comment]
I am not using any permissions with this context yet.
My goal is to enable `delutags.tag.skill` permission for the top players of each skill of mcMMO.
Is that a bad idea?

**Comment by lucko** [comment]
Yeah that's ok but remove
```yaml
magnata: "%vault_eco_top_rank%"
```
 from your config.

**Comment by SrBedrock** [comment]
After removing:
```yaml
magnata: "%vault_eco_top_rank%"
```` 
https://hasteb.in/locajiqu.md

**Comment by lucko** [comment]
Ah okay, so seems like the top rank placeholders are doing MySQL queries, so won't be main thread friendly.

You could maybe ask McMMO to cache these lookups - that could help.

Unfortunately not a problem I can solve though, sorry!
