### ISSUE TITLE
Missing dependency declaration

### ISSUE THREAD

**Issue by SlimeDog** [LuckPerms/ExtraContexts#18]
Spigot 1.15.2 (Jenkins 2596)
ExtraContexts 1.0-b12

**Description**
Beginning with Spigot 1.15.2 (Jenkins 2596), missing dependency declarations are reported in the log on server start-up as WARN messages.

Reference: [https://hub.spigotmc.org/jira/browse/SPIGOT-5546](https://hub.spigotmc.org/jira/browse/SPIGOT-5546)

The relevant log entry is:
```
[22:03:37] [Server thread/WARN]: [ExtraContexts] Loaded class com.sk89q.worldedit.world.World from WorldEdit v7.1.1-SNAPSHOT;4828-e5c3c7a which is not a depend, softdepend or loadbefore of this plugin.
```

**Steps to reproduce the behavior**
- Update Spigot to 1.15.2 latest
- Start the server
- Search the log for 'Loaded class'

**Expected behavior**
Dependencies should be declared in plugin.yml

**Comment by lucko** [comment]
WorldEdit is only a transitive dependency of ExtraContexts.

ExtraContexts depends on WorldGuard, which depends on WorldEdit.

WorldGuard happens to use a class from WorldEdit (`com.sk89q.worldedit.world.World`) as part of its API, which ExtraContexts uses, hence triggering the warning message.

So in my opinion, this is an issue with the logging Spigot is doing.
