### ISSUE TITLE
Suggestion/Issue: updateCommands() when gamemode changes

### ISSUE THREAD

**Issue by accLarson** [LuckPerms/ExtraContexts#19]
When a player has a LP permission with a gamemode context _(for example essentials.tp with context gamemode=spectator)_ The command is not registered to that player when they first connect in survival mode. When the player enters the gamemode _(spectator)_ and then begin to type the command _(/tp player)_ there is no tab completion and the command appears red even though the command WILL run properly

Should https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#updateCommands-- be ran when gamemodes are changed and `gamemode: true` is set in extracontexts' config.yml?

**Comment by ms5984** [comment]
I would agree; though, I am not sure what the design stance is when it comes to calculators storing (last) states. @lucko Are we able to run code that accesses the main thread?

**Comment by Laarryy** [comment]
Should be fixed now - see here for code:

https://github.com/LuckPerms/LuckPerms/blob/master/bukkit/src/main/java/me/lucko/luckperms/bukkit/context/BukkitPlayerCalculator.java#L148
https://github.com/LuckPerms/LuckPerms/blob/master/bukkit/src/main/java/me/lucko/luckperms/bukkit/listeners/BukkitCommandListUpdater.java#L78
