### ISSUE TITLE
Suggestion: Vanilla Team context

### ISSUE THREAD

**Issue by Phoenix616** [LuckPerms/ExtraContexts#20]
It would be useful in certain situations to use Vanila team names as contexts.

In my case this would be useful to block certain commands/functions when a user joins a certain command block minigame but I would imagine that the reverse (only giving permissions in the minigame) might be useful too.

**Comment by lucko** [comment]
Managed to mess up the merge commit message, but it's here: 7033b5fdf03acfa70d94dfb09d02fec98eb569e6

Thanks Phoenix :)
