### ISSUE TITLE
Going from version 108 to latest (138-147)

### ISSUE THREAD

**Issue by RawrMaoster** [LuckPerms/ExtraContexts#22]
**Current files im using:**
LuckPerms-Velocity-5.0.147
LuckPerms-Bukkit-5.0.108

**Server Type:**
Mohist-3df2a98-server.jar (Forge Spigot Paper)

**Link to error message:**
https://pastebin.com/ik0dp8jD

**Description:**
When i use any available version over 108 the error message above crash loops and displaces @ every plugin with same error message.

Even tried to use 1.8.6 instead of 1.8.5 Special source see if i could but the Mohist re-downloads 1.8.5 so im unsure if it would even fix anything.

Recently switching from Sponge to Mohist.

Also cant find any versions between 108 to 138 to test where it breaks.

Thanks for reading,
Aperture Gaming Founder

**Comment by lucko** [comment]
Wrong repo to report on, but ya has been fixed already: 13ebc87b29db80b097dbe3ca785811db4666c7e7
