### ISSUE TITLE
ExtraContexts wg-region doesn't work

### ISSUE THREAD

**Issue by Jowany** [LuckPerms/ExtraContexts#26]
Hi! I tried enabling worldguard in config for using wg-region permission. To confirm context is working I tried `/lp user <user> info`  but wg-region wasn't there. 
I am using latest LuckPerms v5.1.26, latest worldguard 7.0.4-beta1 ExtraContexts build #14 from 25.6.2020

Config:
```
# ExtraContexts
# made with <3 by Luck


# Set a provider to true to enable it.
# Contexts are explained in more detail here:
# https://github.com/lucko/LuckPerms/wiki/Context


# Provides the 'wg-region' context.
# Returns the name of each WorldGuard region the player is currently in.
#
# e.g. wg-region=spawn
worldguard: true

# Provides the 'gamemode' context.
# Returns the players current gamemode.
#
# e.g. gamemode=creative
gamemode: true

# Provides the 'dimension' context.
# Returns the type of the players current world.
#
# e.g. dimension=nether
dimension: false

placeholderapi: true
placeholderapi-placeholders:
  allowflight: "%player_allow_flight%"
```

**Comment by Laarryy** [comment]
Please let us know if you're still encountering this in a new issue - as far as we know, this is fixed and working properly in the latest versions of LP and WG. Sorry for the long wait!
