### ISSUE TITLE
WG Flag calculator causes overflow?/exceptions

### ISSUE THREAD

**Issue by wizjany** [LuckPerms/ExtraContexts#27]
https://github.com/LuckPerms/ExtraContexts/blob/9de1e3e777ec3615892a400ae0d5a2d31878b1fc/src/main/java/me/lucko/extracontexts/calculators/WorldGuardFlagCalculator.java#L28

Unfortunately terrible log, provided by a user using multicraft but here: https://gist.github.com/b2e632188bfb85b606244dfaca67c4c4

basically checking applicable flags requires knowing if the user is a member of the given region, which may require knowing if the user is a member of a group, which requires the context to be checked, which requires checking applicable flags and recurse...

**Comment by lucko** [comment]
I see, thanks for the info.

I don't see a way around this, I guess the safest solution is to just remove the flag calculator from ExtraContexts

**Comment by WayneBuckhanan** [comment]
[WorldGuardWrapper](https://github.com/CodeMC/WorldGuardWrapper) appears to have updated the queryApplicableFlags() method just after the version ExtraContexts currently depends upon.

Updating WorldGuardWrapper to version 1.2.0-SNAPSHOT resolved this issue for me.

```
    <repositories>
        <repository>
            <id>codemc-repo</id>
            <url>https://repo.codemc.org/repository/maven-public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.codemc.worldguardwrapper</groupId>
            <artifactId>worldguardwrapper</artifactId>
            <version>1.2.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
```

Not sure this is worth a pull request, but can put one together if you really want.

This looks like it should also resolve #29, #32, #34, and #35.
Enjoy!

**Comment by Laarryy** [comment]
This is almost definitely fixed on the latest versions of LP, and WG! If it isn't and anyone is still encountering it, please open a new issue. If not, nothing to do!

**Comment by wizjany** [comment]
I don't know why updating the method would have fixed this. this is a fundamental design flaw in EC - you cannot produce permissions based on the result of something that consumes permissions. This is definitely still an issue.
