### ISSUE TITLE
NPE thrown by me.lucko.extracontexts.calculators.WorldGuardFlagCalculator whilst calculating the context of subject CraftPlayer

### ISSUE THREAD

**Issue by ghost** [LuckPerms/ExtraContexts#29]
[extracontexts NPE.txt](https://github.com/LuckPerms/ExtraContexts/files/5073036/extracontexts.NPE.txt)

**Comment by ms5984** [comment]
I'm on WG v7, and so far haven't noticed this problem on my server. I am not using React, however; may I ask, what release of WorldGuard are you using, and is the player online and in the world?

**Comment by ghost** [comment]
The latest version, and yes.

**Comment by ms5984** [comment]
Welp, just tested 7.0.3 (which doesn't officially support 1.16.x) for fun, didn't get an NPE but I did get a StackOverflow from a recursive lookup #27 <maybe a bit like that
Are you using 7.0.4 beta 1?
Also, I'm on paper 1.16.2 build 145, if that helps.

**Comment by ghost** [comment]
Don't worry about it. I've been told it's a known issue.

**Comment by Nezz202** [comment]
Hi. Is this still not working correctly, with the latest version of WG/LP and ExtraContexts? It's not for me, however any suggestions or workarounds would be appreciated if there are any soluions to this. :)

**Comment by Laarryy** [comment]
This is almost definitely fixed on the latest versions of LP, and WG! If it isn't and you still encounter it, please open a new issue. If not, no worries.
