### ISSUE TITLE
Luckperms placeholder crash

### ISSUE THREAD

**Issue by Curtis73** [LuckPerms/ExtraContexts#31]
Hey there, I get the following error whenever I try and use luckperms placeholders in the PlaceholderAPI section of ExtraContexts:
https://hastebin.com/yimofodixa.md
The server spews this out for a minute or two before crashing

**Comment by underscore11code** [comment]
What would your specific LP placeholder be that is triggering that?

**Comment by Curtis73** [comment]
I'm using the `%luckperms_meta_<metakey>%` placeholder

**Comment by underscore11code** [comment]
Are you perhaps using that on a meta node? Maybe the meta node that's in the placeholder?

If you look at that stacktrace, you'll see that it loops through Luckperms Context -> Placeholder API -> back to Luckperms -> back to PAPI -> ... This seems like you've somehow made a loop.

**Comment by Laarryy** [comment]
As far as I know you cannot use any luckperms placeholders in extracontexts as it becomes recursive and does exactly what _11 said.

**Comment by Curtis73** [comment]
Ahh, that's a pain - looks like I'll have to try something else.

Thanks everyone!
