### ISSUE TITLE
Exception Thrown

### ISSUE THREAD

**Issue by srnyx** [LuckPerms/ExtraContexts#35]
[https://github.com/lucko/LuckPerms/issues/2819](https://github.com/lucko/LuckPerms/issues/2819)

**Comment by speed-MikeM** [comment]
I've got exactly the same issue.
No worldguard flags are used yet in luckoperms as the denying pvp wasn't working.
Seems like it the issue pops-up as soon as a region is active.

**Comment by srnyx** [comment]
Realized this is a duplicate of https://github.com/LuckPerms/ExtraContexts/issues/32
