### ISSUE TITLE
Issue in pom.xml

### ISSUE THREAD

**Issue by wfjsw** [LuckPerms/ExtraContexts#36]
https://github.com/LuckPerms/ExtraContexts/blob/1323f1826d4faeadedee9b1bc29fe291cdfb65ed/pom.xml#L39-L45

When opening the project within IDEA on Windows, it starts to try to load the whole `C:` onto this project.

**Comment by Laarryy** [comment]
@lucko not sure the idea behind this decision - how would you like to resolve this one?
