### ISSUE TITLE
WG 7 Spigot 1.13.1

### ISSUE THREAD

**Issue by gorlilla** [LuckPerms/ExtraContexts#5]
is the wg-region context supplied via ExtraContexts supposed to work when using LP 4.3.11 (Dev789) with Spigot 1.13.1 server? when ExtraContexts has worldguard true i  see context register but  get NoSuchMethod errors when it is called and no context field in player info. it appears to be calling WG behind bukkit instead of direct calls (WG 7 engine change?) -- am i doing something wrong or is it currently broken? (asked in discord; suggested posting as issue)

`[LuckPerms] An exception was thrown by me.lucko.extracontexts.calculators.WorldGuardCalculator whilst calculating the context of subject CraftPlayer{name=gorlilla}
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;`

**Comment by lucko** [comment]
Fixed in 458a4f724d946257b2a06a9293219f2186c4ee92
